name: Release Drafter

on:
  workflow_run:
    workflows: ['Deploy Pipeline']
    types:
      - completed

jobs:
  update_release_draft:
    name: Draft Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@v5.12.1
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
